//EXEMPLO QUE FOI USADO NO NAVEGADOR PARA EXPLICAR O CALLBACK NO FRONT END DO JAVASCRIPT
//USE ESTE CÓDIGO ABAIXO NA AREA DE DESENVOLVEDOR E DEPOIS DE COLAR O CODIGO CLIQUE EM ENTER
//LOGO EM SEGUIDA CLIQUE NA PÀGINA(PODE SER NA INICIA DO CHROME)
document.getElementsByTagName('body')[0].onclick = function (e){
console.log('O evento ocorreu!')
}
